FROM openjdk:8-jdk-alpine
WORKDIR /workspace
RUN apk update \
    && mkdir -p /workspace/ \
    && apk add wget \
    && wget http://www-eu.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz \
    && tar -xvzf apache-maven-3.3.9-bin.tar.gz
ENV  M2_HOME /workspace/apache-maven-3.3.9
ENV  PATH ${M2_HOME}/bin:${PATH}
COPY . /workspace/
WORKDIR /workspace/source/user-org-service
RUN mvn clean install -DskipTests
WORKDIR /workspace/source/user-org-service
RUN mvn play2:dist
